export interface Theme {
    name: string;
    properties: any;
}

export const light: Theme = {
    name: 'light',
    properties: {
        '--text-color': 'steelblue',
        '--background-color': '#f5f7f8',
        '--pannel-header-color': '#cde6fa',
        '--toolbar-background-color': '#ffffff',
        '--toolbar-color': 'cornflowerblue',
        '--table-border-color': '#c8c8c8',
        '--table-th-background': '#f4f4f4',
        '--table-th-color': 'black',
        '--table-td-background': 'inherit',
        '--table-td-color': 'black',
        '--table-caption': '#eee3e3',
        '--table-caption-label': 'black',
        '--anchor': 'black',
        '--anchor-leftmenu': 'black',
        '--pannel-title-background': '#cde6fa',
        '--pannel-border': '#7fbcec',
        '--pannel-footer': 'white',
        '--pannel-color': 'black',

        '--dialog-title-background': '#cde6fa',
        '--dialog-title-color': 'black',
        '--dialog-content': 'white',
        '--dialog-footer': 'white',

        '--label': 'steelblue',
        '--overlaypanel-background': 'aliceblue',
        '--button-group-background': '#cde6fa',
        '--button-group-border': '#c8c8c8',
        '--button-disabled-background': '#007ad9',
        '--button-disabled-border': '#007ad9',
        '--button-disabled-color': '#ffffff',
        '--section-group-background': 'seashell',
        '--section-group-border': '#c8c8c8',
        '--section-group-label-color': '#00265c',
        '--paginator-color': 'black',
        '--paginator-background': 'seashell',

        '--panelmenu-header-link': 'white',
        '--panelmenu-header-bg': '#007ad9',
        '--panelmenu-header-notactive-bg': '#dbdbdb',
        '--panelmenu-header-notactive-color': '#ffff',
        '--tabview-tab-bgcolor': '#007ad9',
        '--tabview-tab-bordercolor': '#007ad9',
        '--tabview-panel-bgcolor': '#ffffff',
    }
};

export const classic: Theme = {
    name: 'dark',
    properties: {
        '--text-color': 'yellow',
        '--background-color': '#00265c',
        '--pannel-header-color': '#cde6fa',
        '--toolbar-background-color': '#ffffff',
        '--toolbar-color': 'cornflowerblue',
        '--table-border-color': '#808080',
        '--table-th-background': 'seashell',
        '--table-th-color': '#00265c',
        '--table-td-background': '#00265c',
        '--table-td-color': 'yellow',
        '--table-caption': '#f5f5dc',
        '--table-caption-label': '#00265c',
        '--anchor': 'whitesmoke',
        '--anchor-leftmenu': '#00265c',
        '--pannel-title-background': 'lavender',
        '--pannel-border': '#7fbcec',
        '--pannel-footer': 'whitesmoke',
        '--pannel-color': '#00265c',
        '--dialog-title-background': 'seashell',
        '--dialog-title-color': '#00265c',
        '--dialog-content': '#00265c',
        '--dialog-footer': 'whitesmoke',
        '--label': 'yellow',
        '--overlaypanel-background': '#00265c',
        '--button-group-background': '#cde6fa',
        '--button-group-border': '#c8c8c8',
        '--button-disabled-background': 'grey',
        '--button-disabled-border': 'grey',
        '--button-disabled-color': 'white',
        '--section-group-background': 'lavender',
        '--section-group-border': 'lavender',
        '--section-group-label-color': '#00265c',
        '--paginator-color': '#00265c',
        '--paginator-background': 'whitesmoke',

        '--panelmenu-header-link': 'yellow',
        '--panelmenu-header-bg': '#00265c',
        '--panelmenu-header-notactive-bg': '#dbdbdb',
        '--panelmenu-header-notactive-color': '#00265c',
        '--tabview-tab-bgcolor': '#00265c',
        '--tabview-tab-bordercolor': '#ffffff',
        '--tabview-panel-bgcolor': '#00265c',
    }
};

export const dark: Theme = {
    name: 'dark',
    properties: {
        '--text-color': '#dedede',
        '--background-color': '#3f3f3f',
        '--pannel-header-color': '#cde6fa',
        '--toolbar-background-color': '#ffffff',
        '--toolbar-color': 'cornflowerblue',
        '--table-border-color': '#191919',
        '--table-th-background': '#252525',
        '--table-th-color': '#dedede',
        '--table-td-background': '#323232',
        '--table-td-color': '#dedede',
        '--table-caption': '#191919 ',
        '--table-caption-label': '#dedede',
        '--anchor': 'cyan',
        '--anchor-leftmenu': '#00265c',
        '--pannel-title-background': '#191919',
        '--pannel-border': '#191919',
        '--pannel-footer': '#323232',
        '--pannel-color': '#dedede',
        '--dialog-title-background': '#191919',
        '--dialog-title-color': '#dedede',
        '--dialog-content': '#323232',
        '--dialog-footer': '#323232',
        '--label': '#ffffff',
        '--overlaypanel-background': '#323232',
        '--button-group-background': '#323232',
        '--button-group-border': '#191919',
        '--button-disabled-background': 'whitesmoke',
        '--button-disabled-border': 'silver',
        '--button-disabled-color': 'grey',
        '--section-group-background': '#323232',
        '--section-group-border': '#191919',
        '--section-group-label-color': '#dedede',
        '--paginator-color': '#dedede',
        '--paginator-background': '#252525',

        '--panelmenu-header-link': '#dedede',
        '--panelmenu-header-bg': '#191919',
        '--panelmenu-header-notactive-bg': '#dbdbdb',
        '--panelmenu-header-notactive-color': '#323232',
        '--tabview-tab-bgcolor': '#191919',
        '--tabview-tab-bordercolor': '#ffffff',
        '--tabview-panel-bgcolor': '#3f3f3f',
    }
};
